# load-web-page-puppeteer-mocha

name: Build and Test

on: [push]

jobs:
  build:
    # runs-on: ubuntu-latest
    # Error: Failed to launch the browser process! No usable sandbox!
    # https://issues.chromium.org/issues/373753919
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6    #see: https://github.com/actions/checkout/releases
      - uses: actions/setup-node@v6  #see: https://github.com/actions/setup-node/releases
      - run: npm install
      - run: npm test
